require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.1
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/unicorn.conf.rb'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'
    - 'config/environments/development.rb'

Rails/InverseOf:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ContextMethod:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Max: 4

RSpec/ImplicitExpect:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/rooms_controller.rb'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/GlobalVars:
  Exclude:
    - 'config/unicorn/production.rb'

Style/MutableConstant:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/StringLiterals:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 190

Lint/SuppressedException:
  Exclude:
    - 'config/unicorn/production.rb'
