require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.1
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'
    - 'config/environments/development.rb'

## 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 190
