default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { "password" } %>
  socket: /tmp/mysql.sock
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  database: myapp_development

test:
  <<: *default
  username: root
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { "password" } %>
  socket: /tmp/mysql.sock
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: localhost